import type { Metadata } from "next";
import Link from "next/link";
import { Shield, Eye, Cookie, Trash2 } from "lucide-react";
import { Breadcrumbs } from "@/components/ui";
import { PAGE_BREADCRUMBS } from "@/lib/breadcrumbs";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Learn how NumberGenerator.ai protects your privacy. No tracking, no ads, no data collection. All generation happens locally in your browser.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white dark:bg-black">
      <div className="max-w-3xl mx-auto px-4 py-12 md:py-16">
        {/* Breadcrumb */}
        <div className="mb-8">
          <Breadcrumbs items={PAGE_BREADCRUMBS["/privacy"]} />
        </div>

        {/* Header */}
        <header className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 rounded-2xl bg-zinc-100 dark:bg-zinc-900">
              <Shield className="w-8 h-8 text-zinc-900 dark:text-zinc-100" />
            </div>
            <h1 className="text-3xl md:text-4xl font-black tracking-tight">
              Privacy Policy
            </h1>
          </div>
          <p className="text-lg text-zinc-600 dark:text-zinc-400">
            Last updated:{" "}
            {new Date().toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </p>
        </header>

        {/* Summary Card */}
        <div className="bg-zinc-50 dark:bg-zinc-950 rounded-2xl border border-zinc-200 dark:border-zinc-800 p-6 mb-12">
          <h2 className="text-xl font-bold mb-4">Key Takeaway</h2>
          <p className="text-lg text-zinc-700 dark:text-zinc-300">
            <strong>
              We don&apos;t collect, store, or track any personal data.
            </strong>{" "}
            All number generation happens locally in your browser using
            cryptographically secure random number generation. Nothing is sent
            to our servers.
          </p>
        </div>

        {/* Privacy Sections */}
        <section className="space-y-8">
          {/* No Data Collection */}
          <div className="flex gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-xl bg-green-100 dark:bg-green-900/30 flex items-center justify-center">
                <Eye className="w-6 h-6 text-green-600 dark:text-green-400" />
              </div>
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold mb-3">No Data Collection</h2>
              <p className="text-zinc-600 dark:text-zinc-400 mb-3">
                NumberGenerator.ai does not collect, store, or transmit any
                personal information, usage data, or generated results. When you
                use our tools:
              </p>
              <ul className="list-disc list-inside space-y-2 text-zinc-600 dark:text-zinc-400">
                <li>All generation happens locally in your browser</li>
                <li>No cookies are used for tracking</li>
                <li>No analytics or tracking scripts</li>
                <li>No account registration required</li>
                <li>No IP addresses or device fingerprints are logged</li>
              </ul>
            </div>
          </div>

          {/* Local Processing */}
          <div className="flex gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                <Shield className="w-6 h-6 text-blue-600 dark:text-blue-400" />
              </div>
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold mb-3">Local-Only Processing</h2>
              <p className="text-zinc-600 dark:text-zinc-400 mb-3">
                Our random number generators use the Web Crypto API (CSPRNG -
                Cryptographically Secure Pseudo-Random Number Generator) built
                into modern browsers. This means:
              </p>
              <ul className="list-disc list-inside space-y-2 text-zinc-600 dark:text-zinc-400">
                <li>Randomness is generated by your device, not our servers</li>
                <li>Your generated numbers never leave your browser</li>
                <li>The same security model used for HTTPS/TLS encryption</li>
                <li>Suitable for security-sensitive applications</li>
              </ul>
            </div>
          </div>

          {/* Cookies */}
          <div className="flex gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-xl bg-orange-100 dark:bg-orange-900/30 flex items-center justify-center">
                <Cookie className="w-6 h-6 text-orange-600 dark:text-orange-400" />
              </div>
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold mb-3">
                Cookies & Local Storage
              </h2>
              <p className="text-zinc-600 dark:text-zinc-400 mb-3">
                We use minimal storage solely to enhance your user experience:
              </p>
              <ul className="list-disc list-inside space-y-2 text-zinc-600 dark:text-zinc-400">
                <li>
                  <strong>Local Storage:</strong> Saves your recent tools and
                  favorite settings for quick access
                </li>
                <li>
                  <strong>Session Storage:</strong> Temporary data during your
                  current session
                </li>
                <li>
                  <strong>No tracking cookies:</strong> We do not use
                  third-party tracking or advertising cookies
                </li>
              </ul>
              <p className="text-zinc-600 dark:text-zinc-400 mt-3">
                You can clear this data at any time through your browser
                settings or by using the clear data option in our tools.
              </p>
            </div>
          </div>

          {/* Data Retention */}
          <div className="flex gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-xl bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
                <Trash2 className="w-6 h-6 text-red-600 dark:text-red-400" />
              </div>
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold mb-3">
                Data Retention & Deletion
              </h2>
              <p className="text-zinc-600 dark:text-zinc-400">
                Since we do not collect or store any data on our servers, there
                is no data to retain or delete. Any data stored locally in your
                browser (preferences, favorites) can be cleared at any time by:
              </p>
              <ul className="list-disc list-inside space-y-2 text-zinc-600 dark:text-zinc-400 mt-3">
                <li>Clearing your browser cache and storage</li>
                <li>Using the clear option in the app settings</li>
                <li>Using incognito/private browsing mode</li>
              </ul>
            </div>
          </div>

          {/* Third Parties */}
          <div className="flex gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center">
                <Shield className="w-6 h-6 text-purple-600 dark:text-purple-400" />
              </div>
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold mb-3">Third-Party Services</h2>
              <p className="text-zinc-600 dark:text-zinc-400 mb-3">
                We do not use third-party services that process your data.
                Specifically:
              </p>
              <ul className="list-disc list-inside space-y-2 text-zinc-600 dark:text-zinc-400">
                <li>No analytics services (Google Analytics, etc.)</li>
                <li>No advertising networks</li>
                <li>No social media integrations</li>
                <li>No third-party cookies or trackers</li>
              </ul>
            </div>
          </div>

          {/* Children's Privacy */}
          <div className="flex gap-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-xl bg-yellow-100 dark:bg-yellow-900/30 flex items-center justify-center">
                <Shield className="w-6 h-6 text-yellow-600 dark:text-yellow-400" />
              </div>
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold mb-3">
                Children&apos;s Privacy
              </h2>
              <p className="text-zinc-600 dark:text-zinc-400">
                Our service is suitable for all ages and does not collect
                personal information from anyone, including children. Since we
                collect no data, COPPA compliance is inherently maintained.
              </p>
            </div>
          </div>
        </section>

        {/* Contact */}
        <section className="mt-12 p-6 rounded-2xl border border-zinc-200 dark:border-zinc-800">
          <h2 className="text-xl font-bold mb-3">Questions?</h2>
          <p className="text-zinc-600 dark:text-zinc-400">
            If you have any questions about this privacy policy or our
            practices, please contact us at{" "}
            <a
              href="mailto:hello@numbergenerator.ai"
              className="text-zinc-900 dark:text-zinc-100 hover:underline"
            >
              hello@numbergenerator.ai
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
